name = "hessen-rp-polizei"
main = "src/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./public"
binding = "ASSETS"

# Nach dem Erstellen des KV-Namespace (siehe README) hier die echte ID eintragen:
[[kv_namespaces]]
binding = "PH_KV"
id = "HIER_DEINE_KV_NAMESPACE_ID_EINTRAGEN"
